
# SEO settings
title: "Nicolas "
title2: "Cloarec" # default: ""
description: "Research Engineer in Machine Learning."
keywords: "Nicolas, Cloarec, data, science, machine, learning, statistics, optimisation, optimization, KDRSDL, ICCV, geometric, deep, graph, manifold"
url: http://ncloarec.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: UA-XXXXX-XX
# repo: http://github.com/heiswayi/thinkspace
# disqus_shortname: "hnbloggithub"
# twitter_username: "HeiswayiNrird"
# comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Nicolas Cloarec"
  job      : "Research Engineer in Machine Learning"

  bio      : "I recently completed my master degree in Machine Learning from ENS Paris-Saclay (Research Master MVA - one of the oldest and most renowned master in machine learning, both for research and for companies. It became very selective in the past couple of years.) and from ENSAE ParisTech (Master of Engineering - France's top schools of statistics)."
  thumb    : /images/author.jpg
  email    : ncloarec@gmail.com
  url      : http://ncloarec.github.io
  github   : http://github.com/ncloarec

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
